"""add error to jobs

Revision ID: 171c24953406
Revises: 9c46fb3b0917
Create Date: 2026-09-18 11:40:18.693856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171c24953406'
down_revision: Union[str, Sequence[str], None] = '9c46fb3b0917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'error')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
