"""add error to job and material

Revision ID: 9c46fb3b0917
Revises: 6551a5ac2832
Create Date: 2026-09-18 11:34:48.229008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c46fb3b0917'
down_revision: Union[str, Sequence[str], None] = '6551a5ac2832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('error', sa.String(), nullable=True))
    op.add_column('materials', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'error')
    op.drop_column('jobs', 'error')
    # ### end Alembic commands ###
